# Generated by Django 5.2.4 on 2025-10-02 22:57

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'Image du produit', 'verbose_name_plural': 'Images du produit'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Select the dominant color of this product image', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(blank=True, help_text='Optional: Name of the color (e.g., Red, Blue, Black)', max_length=50, verbose_name='Color Name'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Produit'),
        ),
    ]
