# Generated by Django 5.2.4 on 2025-12-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productimage_options_productimage_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Poids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='longueur'),
        ),
        migrations.AddField(
            model_name='product',
            name='metre_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
