# Generated by Django 5.2.4 on 2025-12-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_poids_product_metre_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Poids',
        ),
        migrations.AddField(
            model_name='product',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids en kilogrammes', max_digits=8, null=True, verbose_name='Poids (kg)'),
        ),
    ]
