# Generated by Django 5.2.4 on 2025-11-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_guest_address_order_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Guest Email'),
        ),
    ]
