# Generated by Django 5.2.4 on 2025-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='carr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Carr'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='hauteur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hauteur'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='largeur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largeur'),
        ),
    ]
