# Generated by Django 5.2.4 on 2025-12-11 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_poids_product_metre_price'),
        ('orders', '0005_orderitem_carr_orderitem_hauteur_orderitem_largeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilayaDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Wilaya')),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de livraison')),
            ],
            options={
                'verbose_name': 'Prix de livraison par wilaya',
                'verbose_name_plural': 'Prix de livraison par wilaya',
            },
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='carr',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='hauteur',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='largeur',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix total commande'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Longueur (m)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='metre_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix par mètre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_address',
            field=models.TextField(blank=True, verbose_name='Adresse de l’invité'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de l’invité'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de l’invité'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone de l’invité'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_wilaya',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wilaya de l’invité'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Envoyée'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
