# Generated by Django 5.2.4 on 2025-12-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='metre_price',
        ),
    ]
